owner: "55929738"
team: "18160021"
lastUpdatedBy: "55929738"
lastRevision: 1781868577000
name: prod
color: 120
values:
  - key: baseUrl
    value: https://customer-education.postmanlabs.com
    enabled: true
  - key: apiKey
    value: "1234"
    enabled: true
createdAt: 2026-06-19T10:23:34.000Z
updatedAt: 2026-06-19T11:29:37.000Z
